name: Update Collection JSON

on:
  schedule:
    - cron: '0 0 * * *'  # run every day at midnight UTC
  workflow_dispatch:     

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run fetchCollection.js
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: node src/fetchCollection.js

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add public/audios.json public/videos.json public/weekly-profile.json public/new.json
        git commit -m "Update collection and profile archive" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Upload public folder
      uses: actions/upload-pages-artifact@v3
      with:
        path: './public'

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4
